### PR TITLE
PROP-5 : System should show autocomplete search box on landing page.

### PR DESCRIPTION
**Pull request by sakshigokhru**
## Description
_System should show autocomplete search box on landing page._
_When user type property address it will trigger API call which will return the matching property records in our database. When user select any option from auto complete dropdown or type it and manually hit on Search Property button, then redirected user to property detail page._

## Screenshot
screen shot 2018-09-22 at 12 07 47 pm
screen shot 2018-09-22 at 12 08 59 pm

### CODE REVIEW

**Comment by jjalan** [comment]
@sakshigokhru - When I click on create token and not connected to Metamask account, please change error message as follows:

Please change
'Couldn't get any accounts! Make sure your Ethereum client is configured correctly.'

to

'Please install or login to your Metamask account to continue'.

**Comment by sakshigokhru** [comment]
@jjalan - Changes improved please have a look.

**Comment by jjalan** [comment]
@sakshigokhru - Autocomplete is still not aligned properly.

screen shot 2018-09-19 at 12 33 36 pm

**Comment by sakshigokhru** [comment]
@jjalan - I had improved changes as per our discussion, please have a look.

**Pull request merged**
